/*  =========================================================================
    exo-boricj - generated layer of public API

    Copyright (C) 2014 - 2017 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef EXO_BORICJ_LIBRARY_H_INCLUDED
#define EXO_BORICJ_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>

//  EXO_BORICJ version macros for compile-time API detection
#define EXO_BORICJ_VERSION_MAJOR 1
#define EXO_BORICJ_VERSION_MINOR 0
#define EXO_BORICJ_VERSION_PATCH 0

#define EXO_BORICJ_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define EXO_BORICJ_VERSION \
    EXO_BORICJ_MAKE_VERSION(EXO_BORICJ_VERSION_MAJOR, EXO_BORICJ_VERSION_MINOR, EXO_BORICJ_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined EXO_BORICJ_STATIC
#       define EXO_BORICJ_EXPORT
#   elif defined EXO_BORICJ_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define EXO_BORICJ_EXPORT __declspec(dllexport)
#       else
#           define EXO_BORICJ_EXPORT
#       endif
#   elif defined EXO_BORICJ_EXPORTS
#       define EXO_BORICJ_EXPORT __declspec(dllexport)
#   else
#       define EXO_BORICJ_EXPORT __declspec(dllimport)
#   endif
#   define EXO_BORICJ_PRIVATE
#else
#   define EXO_BORICJ_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define EXO_BORICJ_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define EXO_BORICJ_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  EXO_BORICJ_BUILD_DRAFT_API
#define EXO_BORICJ_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef EXO_BORICJ_BUILD_DRAFT_API
typedef struct _exo_boricj_server_t exo_boricj_server_t;
#define EXO_BORICJ_SERVER_T_DEFINED
#endif // EXO_BORICJ_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef EXO_BORICJ_BUILD_DRAFT_API
#include "exo_boricj_server.h"
#endif // EXO_BORICJ_BUILD_DRAFT_API

#ifdef EXO_BORICJ_BUILD_DRAFT_API
//  Self test for private classes
EXO_BORICJ_EXPORT void
    exo_boricj_private_selftest (bool verbose);
#endif // EXO_BORICJ_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
